### ISSUE TITLE
Publish a Web version to the Github Pages

### ISSUE THREAD

**Issue by terrakok** [fethij/Rijksmuseum#2]
You can find an example of a CI config here: https://github.com/terrakok/compose-material-3-gallery/blob/master/.github/workflows/deploy.yaml

**Comment by fethij** [comment]
https://github.com/fethij/Rijksmuseum/pull/4

**Comment by fethij** [comment]
https://github.com/fethij/Rijksmuseum/pull/4

**Comment by fethij** [comment]
https://fethij.github.io/Rijksmuseum/
