### ISSUE TITLE
Cannot obtain the api  key

### ISSUE THREAD

**Issue by guanpj** [fethij/Rijksmuseum#61]
According to this guide: https://data.rijksmuseum.nl/docs/api/
Before running this app, I should obtain the API key from https://www.rijksmuseum.nl/en/rijksstudio/my/profile
However, after completing the registration for my account, I am still unable to access this site, preventing me from obtaining the API key necessary to run the app.

**Comment by fethij** [comment]
You can use the following api key: MT0CNYQt
